apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hhkg5ud93-nodejs
  janus-idp.io/tekton: hhkg5ud93-nodejs
  backstage.io/kubernetes-id: hhkg5ud93-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hhkg5ud93-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
